CREATE TABLE [dbo].[User]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [GovUkIdentifier] VARCHAR(100) NOT NULL,
    [EmailAddress] VARCHAR(100) NOT NULL,
    [PhoneNumber] VARCHAR(20) NULL,
    [LastLoginAt] DATETIME2 NULL,
    [IsLocked] BIT NOT NULL CONSTRAINT [DF_User_IsLocked] DEFAULT (0),
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [DF_User_CreatedAt] DEFAULT SYSUTCDATETIME()
)
GO